### ISSUE TITLE
Schemas for "pruned" beacon blocks are incorrect

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/beacon-APIs#292]
Refer: https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/blocks/blinded_block.yaml#L34-L39

The schemas have "full" (signed) beacon blocks whereas this endpoint should provide blinded beacon blocks.

AIUI we should update these schemas to the right type -- and taking a look at the other blinded endpoints, I see a similar issue.

**Comment by staccDOTsol** [comment]
Thank you for bringing this to my attention. I apologize for any confusion caused by the incorrect schemas for "pruned" beacon blocks in the beacon API documentation. I will make sure to address this issue and update the schemas accordingly. Your feedback is greatly appreciated in helping us maintain accurate and up-to-date information.

**Comment by dapplion** [comment]
This issue appears fixed.

All blinded_* routes declare the blinded block types for post bellatrix and the full types for pre bellatrix. This is correct, since the pre bellatrix types do not have an execution payload thus full type = blinded type

https://github.com/ethereum/beacon-APIs/blob/ad873a0f8d2c2a7c587dd667274199b2eb00f3ba/apis/beacon/blocks/blinded_block.yaml#L35-L40

please re-open if I'm missing something
