### ISSUE TITLE
Integer representation

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon-APIs#30]
_[Note, this was [previously discussed](https://github.com/ethereum/eth2.0-APIs/issues/9) by a few of us but resurfacing now to make sure everyone on board]_

As discussed on the API call today, we need to decide on integer representation in the API. Using native integers is not favorable due to the JS limitation of 53-bit. The natural choice becomes a string. The two competing ideas are a decimal representation or a hex representation with an `0x` prefix.

* decimal
    * readability
    * already found in this repo (easily changed) and in prysm
* hex
   * conformance with eth1 format   ([reference JSON RPC encoding](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding))
   * faster to convert to integer
   * smaller size to transport

IMO, the readability argument for decimal are a bit more compelling than the eth1 conformance. Conformance with eth1 must be augmented by the fact that we are using little-endian where that is big-endian, and the eth1 API is a separate JSON-RPC.

**Comment by mratsim** [comment]
Sidenote: There was a side item on byte arrays/sequences representation. And there was a strong preference not to use Base64 and hex as well.

**Comment by rolfyone** [comment]
Decimal makes perfect sense to me, I hadn't even really considered displaying them in hex. It's just a shame about javascript interface limitations otherwise I'd have left teku using unbound integer types.

I think lighthouse, Prysm, Teku are all on the same page with strings for unsigned long, and decimal representation.

**Comment by paulhauner** [comment]
We're currently just using integers (not ideal). I'm don't feel strongly but I'd lean towards string for readability.

**Comment by prestonvanloon** [comment]
Prylabs has a strong preference for industry standards conformance. In
particular, we do not support hex encoded strings for binary data or
integers as a strict requirement.

Most of the feedback in favor of hex encoded binary data seems to be for
debugging purposes. Imposing hex encoded binary data requires users to
write their own data models for parsing JSON objects with a byte array
field or use specific eth1 data types / encoding. For example, go Ethereum
has custom json encoder instead of using standard libraries.
https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.9.13/common/hexutil?tab=doc

The same type of issues would apply for ETH2. Users would need to use a
custom JSON encoder instead of the many of existing tools. Using the
default for base64 allows for existing solutions to work out of the box. If
developers need or really want hex encoded strings then perhaps there could
be some eth1 compatibility mode, debug mode, or readability mode. Could we
recommend a “debug” or “readability” mode?

**Comment by rolfyone** [comment]
I think this ticket should stay very focussed on the representation of 64 bit integers, i think binary representation will just muddy the water here.

It does sound like a string with a base10 representation of the number is ok with everyone...

**Comment by mpetrunic** [comment]
Closing this as general consensus was string representation
