### ISSUE TITLE
Endpoint for expected withdrawals for a slot

### ISSUE THREAD

**Issue by avalonche** [ethereum/beacon-APIs#301]
Add an endpoint to fetch the expected withdrawals for some slot.

The endpoint path proposed is /eth/v1/beacon/states/{state_id}/withdrawals.

With the capella upgrade withdrawals are embedded in the payload attributes and currently there is no way to access the withdrawals outside the beacon node for validation. 

With this API, withdrawals in the payload of externally built blocks can be compared with the expected withdrawals to ensure that the two match.

**Comment by rolfyone** [comment]
We could do this to a limited amount, we need the pre-state to compute it and the starting point.

Curious why we want this? Basically the EL is told precisely the withdrawals to include before building a block, so it should get that information up front before it starts... Is there value in an api being provided to show the information?

**Comment by michaelsproul** [comment]
It's useful for external block builders who want to synthesise their own payload attributes without being prompted by the CL. It's part of the reason why we added an API for fetching the randao mix at the head state (https://github.com/ethereum/beacon-APIs/pull/242).

For the expected withdrawals API I think it's essential to provide a `slot` with the query as well so that the CL can advance the state to the right slot. Epoch transitions through empty slots can change the expected set of withdrawals by changing validator balances.

**Comment by mcdee** [comment]
If this is required then perhaps it makes more sense to have a single API call that can provide all of the information required by the builder, rather than having separate calls for each element?

**Comment by ralexstokes** [comment]
yeah, this is something we could combine w/ #244 so that if configured the beacon node just spits out "builder events" for each head it is tracking

**Comment by metachris** [comment]
For reference, this is the implementation in the Flashbots Prysm fork:

* https://github.com/flashbots/prysm/commit/0f0c6082b06303615c4a4c5a95e40f19268cc03f
* https://github.com/flashbots/prysm/commit/bfeb9a575235c9a63b1d46486654748d051aa221

**Comment by rolfyone** [comment]
Does that imply we're not going to integrate it into the events, and an endpoint off a state is sufficient?

**Comment by michaelsproul** [comment]
@rolfyone I think current plan is to have both

**Comment by rolfyone** [comment]
ok so we're approving this one?

**Comment by rolfyone** [comment]
> ok so we're approving this one?

never mind this isn't a PR, bad question.
