### ISSUE TITLE
Clarity on /beacon/headers

### ISSUE THREAD

**Issue by paulhauner** [ethereum/beacon-APIs#75]
Hi there :) I'm looking for some clarity on this line, please:

https://github.com/ethereum/eth2.0-APIs/blob/dcb3cd190e699b18ec19a66d9ca4db9f92ec5a4e/apis/beacon/blocks/headers.yaml#L4

Specifically, what the list of *"current head slot blocks"* contains. I see these possibilities:

1. The canonical head block (single-item list).
1. All blocks that have the same slot as the canonical head block.
1. All blocks that are at the head of the chain.

Either (1) or (3) seems to make sense to me and I'd lead to (1) since (3) is already covered (indirectly) by `debug/beacon/heads`.

**Comment by mpetrunic** [comment]
Yeah my bad for description. Idea was to take current forkchoice head slot and return all blocks at that slot (since response already contains canonical field), I guess thats option 2. (1) is covered by `/v1/beacon/headers/{blockId}`

Since query params are generally considered optional, it was issue what to display if no query params are submitted (in some common sense, we should return paginated all blocks we know of, but I don't think that makes sense).

I'm open to discussing better alternative :slightly_smiling_face:

**Comment by rolfyone** [comment]
raised something v. similar #103

**Comment by rolfyone** [comment]
Happy for me to close this?
